# Generated by Django 4.0.5 on 2022-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='nonce',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
