# Generated by Django 4.0.5 on 2022-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_cert_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='nonce',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
