# Generated by Django 4.0.5 on 2022-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0003_alter_cert_id_alter_cert_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='txnId',
            field=models.CharField(blank=True, default='', max_length=30000),
        ),
    ]
